export type Product = { id: string; slug: string; name: string; shortDescription: string; description: string; price: number; compareAtPrice?: number; category: string; gemstone: string; purpose: string[]; zodiac: string[]; material: string; certification?: string; stock: number; sku: string; rating?: number; reviewCount?: number; featured?: boolean; bestseller?: boolean; newArrival?: boolean; color: string; image: string; variants?: string[] };

// DEMO CATALOGUE — replace this file (or adapt its shape to a CMS) with verified AVNTA GEMS inventory before launch.
export const products: Product[] = [
  { id: 'ag-001', slug: 'ruby-solitaire-ring', name: 'Ruby Solitaire Ring', shortDescription: 'A vivid red stone in a considered everyday setting.', description: 'A demonstration product description. Add verified stone, setting, origin, certification and care details before publishing.', price: 18500, compareAtPrice: 22000, category: 'Rings', gemstone: 'Ruby', purpose: ['Confidence', 'Love'], zodiac: ['Aries', 'Leo'], material: 'Sterling silver', stock: 4, sku: 'DEMO-RUB-001', rating: 4.8, reviewCount: 0, featured: true, bestseller: true, color: '#7e1d2b', image: 'ruby', variants: ['Size 6', 'Size 7', 'Size 8'] },
  { id: 'ag-002', slug: 'emerald-orbit-pendant', name: 'Emerald Orbit Pendant', shortDescription: 'A quiet green focal point for every day.', description: 'A demonstration product description. Add verified AVNTA GEMS product details before publishing.', price: 14200, category: 'Pendants', gemstone: 'Emerald', purpose: ['Peace', 'Success'], zodiac: ['Taurus', 'Gemini'], material: 'Gold vermeil', stock: 6, sku: 'DEMO-EME-002', rating: 4.7, reviewCount: 0, featured: true, color: '#17614a', image: 'emerald' },
  { id: 'ag-003', slug: 'blue-sapphire-stud-earrings', name: 'Blue Sapphire Stud Earrings', shortDescription: 'A deep blue pair with a pared-back silhouette.', description: 'A demonstration product description. Add verified AVNTA GEMS product details before publishing.', price: 16800, category: 'Earrings', gemstone: 'Blue Sapphire', purpose: ['Focus', 'Protection'], zodiac: ['Capricorn', 'Aquarius'], material: 'Sterling silver', stock: 3, sku: 'DEMO-SAP-003', rating: 4.9, reviewCount: 0, bestseller: true, color: '#213d76', image: 'sapphire' },
  { id: 'ag-004', slug: 'citrine-sun-bracelet', name: 'Citrine Sun Bracelet', shortDescription: 'A warm, light-catching strand.', description: 'A demonstration product description. Add verified AVNTA GEMS product details before publishing.', price: 6400, category: 'Bracelets', gemstone: 'Citrine', purpose: ['Prosperity', 'Confidence'], zodiac: ['Gemini', 'Virgo'], material: 'Gold-tone clasp', stock: 11, sku: 'DEMO-CIT-004', rating: 4.6, reviewCount: 0, newArrival: true, color: '#c47e17', image: 'citrine' },
  { id: 'ag-005', slug: 'rose-quartz-heart-necklace', name: 'Rose Quartz Heart Necklace', shortDescription: 'A softly sculpted stone on a fine chain.', description: 'A demonstration product description. Add verified AVNTA GEMS product details before publishing.', price: 7800, category: 'Necklaces', gemstone: 'Rose Quartz', purpose: ['Love', 'Peace'], zodiac: ['Taurus', 'Libra'], material: 'Gold vermeil', stock: 8, sku: 'DEMO-ROS-005', rating: 4.5, reviewCount: 0, featured: true, color: '#b97880', image: 'rose-quartz' },
  { id: 'ag-006', slug: 'moonstone-cabochon', name: 'Moonstone Cabochon', shortDescription: 'A loose stone selected for a luminous finish.', description: 'A demonstration product description. Add verified AVNTA GEMS product details before publishing.', price: 9200, category: 'Loose Stones', gemstone: 'Moonstone', purpose: ['Peace', 'Protection'], zodiac: ['Cancer'], material: 'Natural stone', stock: 2, sku: 'DEMO-MOO-006', rating: 4.8, reviewCount: 0, color: '#9ba6ba', image: 'moonstone' },
  { id: 'ag-007', slug: 'amethyst-arc-ring', name: 'Amethyst Arc Ring', shortDescription: 'Violet geometry with a slim profile.', description: 'A demonstration product description. Add verified AVNTA GEMS product details before publishing.', price: 11800, category: 'Rings', gemstone: 'Amethyst', purpose: ['Peace', 'Focus'], zodiac: ['Aquarius', 'Pisces'], material: 'Sterling silver', stock: 5, sku: 'DEMO-AME-007', rating: 4.7, reviewCount: 0, newArrival: true, color: '#65427a', image: 'amethyst' },
  { id: 'ag-008', slug: 'tiger-eye-grounding-bracelet', name: 'Tiger Eye Grounding Bracelet', shortDescription: 'Warm, polished beads for a grounded look.', description: 'A demonstration product description. Add verified AVNTA GEMS product details before publishing.', price: 4800, category: 'Bracelets', gemstone: 'Tiger Eye', purpose: ['Confidence', 'Protection'], zodiac: ['Gemini', 'Leo'], material: 'Natural stone', stock: 12, sku: 'DEMO-TIG-008', rating: 4.4, reviewCount: 0, bestseller: true, color: '#71451f', image: 'tiger-eye' },
];

export const categories = [
  ['Gemstones', 'Loose stones, selected with intention.', 'gemstones', '#ac6b44'], ['Rings', 'Modern settings with a lasting point of view.', 'rings', '#63444a'], ['Bracelets', 'An easy ritual for every day.', 'bracelets', '#8e734d'], ['Pendants', 'Close to the heart.', 'pendants', '#496e5d'], ['Necklaces', 'Quiet statements, beautifully worn.', 'necklaces', '#755450'], ['Earrings', 'Light-catching finishing touches.', 'earrings', '#435e7f'],
] as const;
export const purposes = ['Wealth', 'Love', 'Protection', 'Success', 'Peace', 'Confidence', 'Prosperity'];
export const zodiac = [['Aries','Ruby'],['Taurus','Emerald'],['Gemini','Citrine'],['Cancer','Moonstone'],['Leo','Ruby'],['Virgo','Citrine'],['Libra','Rose Quartz'],['Scorpio','Red Coral'],['Sagittarius','Yellow Sapphire'],['Capricorn','Blue Sapphire'],['Aquarius','Amethyst'],['Pisces','Amethyst']];
export const articles = [{ slug: 'understanding-gemstone-certification', title: 'Understanding gemstone certification', category: 'Buying Guide', excerpt: 'The questions worth asking before you choose a stone.' }, { slug: 'how-to-choose-an-emerald', title: 'How to choose a natural emerald', category: 'Gemstone Guide', excerpt: 'A considered introduction to colour, clarity and care.' }, { slug: 'caring-for-gemstone-jewellery', title: 'Caring for gemstone jewellery', category: 'Care Guide', excerpt: 'A simple ritual for pieces designed to be worn.' }];
export const formatPrice = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);
export const findProduct = (slug: string) => products.find((p) => p.slug === slug);
